# Generated by Django 6.0.3 on 2026-03-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenant', '0002_tenant_connection_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='connection_string',
            field=models.TextField(blank=True, help_text='Encrypted connection URL for database tenants.', null=True),
        ),
    ]
