# Generated by Django 6.0.3 on 2026-03-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenant', '0005_tenant_provisioning_connection_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='connection_alias',
            field=models.CharField(blank=True, help_text="Required when isolation_mode='database'.", max_length=100, null=True),
        ),
    ]
