# Generated by Django 6.0.3 on 2026-03-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='connection_alias',
            field=models.CharField(blank=True, help_text="Required when isolation_mode='database'.", max_length=100, null=True, unique=True),
        ),
    ]
