# Generated by Django 6.0.3 on 2026-03-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenant', '0003_tenant_connection_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='provisioning_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], db_index=True, default='auto', max_length=20),
        ),
    ]
